---
apiVersion: v1
kind: Service
metadata:
  name: results 
  labels: 
    role: results
  namespace: instavote
spec:
  selector:
    role: results
  ports:
    - port: 80
      targetPort: 80
      #nodePort: 32000
  type: LoadBalancer


